Repository couchbaselabs/node-ottoman, pull requests merged in 2021-02, with the labels that each got.

#398 feat(i-374): support for lean
  __test__/query-lean.spec.ts
  __test__/testData.ts
  src/handler/find/find-by-id-options.ts
  src/handler/find/find-options.ts
  src/handler/find/find.ts
  src/model/create-model.ts
Labels: P2, enhancement

#397 feat(i-373): create support for Immutable
  __test__/schema-inmutable.spec.ts
  src/model/create-model.ts
  src/model/document.ts
  src/schema/interfaces/schema.types.ts
Labels: P2, enhancement

#402 feat(i-393): ottoman errors are more Generic
  __test__/errors-name.spec.ts
  __test__/global-plugin.spec.ts
  __test__/indexes.spec.ts
  __test__/model-crud.spec.ts
  __test__/model-populate.spec.ts
  __test__/ottoman-instances.spec.ts
  __test__/query-builder.spec.ts
  __test__/schema.complex.types.spec.ts
  __test__/schema.native.types.spec.ts
  __test__/schema.types.spec.ts
  __test__/server-ops.spec.ts
  __test__/utils.spec.ts
  src/exceptions/ottoman-errors.ts
  src/handler/utils.ts
  src/model/create-model.ts
  src/model/document.ts
  src/model/index/n1ql/build-index-query.ts
  src/model/index/n1ql/extract-index-field-names.ts
  src/model/index/view/build-view-index-query.ts
  src/ottoman/ottoman.ts
  src/plugins/global-plugin-handler-error.ts
  src/plugins/global-plugin-handler.ts
  src/query/exceptions.ts
  src/query/helpers/builders.ts
  src/query/query.ts
  src/schema/errors/build-schema-error.ts
  src/schema/errors/validation-error.ts
  src/schema/helpers/fn-schema.ts
  src/schema/types/array-type.ts
  src/schema/types/date-type.ts
  src/schema/types/embed-type.ts
  src/schema/types/number-type.ts
  src/schema/types/reference-type.ts
  src/schema/types/string-type.ts
  src/types.d.ts
  src/utils/cast-strategy.ts
  src/utils/jp-parse.ts
  src/utils/parse-errors.ts
  src/utils/path-to-n1ql.ts
Labels: P0, enhancement

#400 feat(schema): implement schema add function, to extend schema from ot…
  __test__/create-many.spec.ts
  __test__/schema.add.spec.ts
  src/schema/helpers/fn-schema.ts
  src/schema/schema.ts
  vuepress/guides/schema.md
Labels: enhancement

#405 feat(i-381): documentation issues - Home
  README.md
  __test__/server-ops.spec.ts
  vuepress/guides/schema.md
Labels: P1, enhancement
