Repository couchbaselabs/node-ottoman, pull requests merged in 2021-03, with the labels that each got.

#406 feat(i-351): add support for schema string type options
  __test__/schema.types.spec.ts
  src/schema/types/string-type.ts
Labels: P3, enhancement

#411 Fb ottoman with typescript latest
  __test__/hooks.spec.ts
  __test__/model-crud.spec.ts
  __test__/model-schema-integration.spec.ts
  package.json
  src/model/model.types.ts
  yarn.lock
Labels: P1, dependencies, enhancement

#416 feat(i-394): documentation - Schema
  __test__/schema.types.spec.ts
  src/schema/types/mixed-type.ts
  vuepress/guides/schema.md
Labels: P1

#425 feat(i-423): ValidationError messages are Inconsistent
  __test__/schema.native.types.spec.ts
  src/schema/helpers/date-minmax.ts
  src/schema/helpers/number-minmax.ts
  src/schema/types/date-type.ts
  src/schema/types/number-type.ts
Labels: P1

#427 test: add test case for ANY X SATISFIES where clause
  __test__/query-builder.spec.ts
  __test__/query-select.spec.ts
  src/model/index/n1ql/build-index-query.ts
  src/query/helpers/builders.ts
  src/query/interface/query.types.ts
  vuepress/guides/query-builder.md
Labels: enhancement
