Repository couchbaselabs/node-ottoman, pull requests merged in 2021-04, with the labels that each got.

#431 feat(query): add $ignoreCase property to the query builder where operators
  __test__/ignore-case.spec.ts
  __test__/schema-inmutable.spec.ts
  src/model/model.ts
  src/query/helpers/builders.ts
  src/query/interface/query.types.ts
  src/query/query.ts
  vuepress/guides/model.md
  vuepress/guides/query-builder.md
Labels: enhancement

#420 fix(lean): fix issues with lean option in findById method
  __test__/query-lean.spec.ts
  src/handler/find/find.ts
  src/model/create-model.ts
Labels: bug

#421 fix(immutable): add mutation function updateById default immutable strategy to true
  __test__/schema-inmutable.spec.ts
  src/model/create-model.ts
Labels: bug

#440 feat(ignorecase): ignoreCase in findOptions and update docs
  __test__/ignore-case.spec.ts
  src/handler/find/find-options.ts
  src/handler/find/find.ts
  src/model/model.ts
  src/query/base-query.ts
  src/query/helpers/builders.ts
  src/query/interface/query.types.ts
  src/query/query.ts
  vuepress/guides/model.md
  vuepress/guides/query-builder.md
Labels: P1, enhancement

#441 feat(projection): projection should return back only the fields that are necessary
  __test__/model-find-projection.spec.ts
  __test__/schema-cast.spec.ts
  src/handler/find/find.ts
  src/utils/populate/can-be-populated.ts
Labels: P2, enhancement

#443 feat(i-423): for min/max length update messages
  __test__/schema.native.types.spec.ts
  src/schema/helpers/number-minmax.ts
Labels: P1
